# Dockerfile para una aplicación de React
# Imagen base

FROM node:latest

# Directorio de trabajo

WORKDIR /app

# Copiar el package.json y el package-lock.json

COPY package*.json ./

# Instalar dependencias

RUN npm install

# Copiar el resto de los archivos

COPY . .

# Exponer el puerto 3000

EXPOSE 3000

# Añadir variables de entorno

ENV REACT_APP_BACKEND_IP=192.168.1.130
# Comando para ejecutar la aplicación

CMD ["npm", "start"]
